# name of the workflow
name: Rust

# run workflow when the condition is met
on:
# run when code is pushed on the `main` branch
  push:
    branches: [ "master" ]
# run when a pull request to the `main` branch
  pull_request:
    branches: [ "master" ]

# env variables
env:
  CARGO_TERM_COLOR: always

# jobs
jobs:
# job name
  build:
  # os to run the job on support macOS and windows also
    runs-on: ubuntu-latest
# steps for job
    steps:
    # this will get the code and set the git
    - uses: actions/checkout@v3
    # run the build
    - name: Build
    # using cargo to build
      run: cargo build --release

    # for deployment
    - name: make dir
    # create a directory
      run: mkdir app
    # put the app in it
    - name: copy
      run: mv ./target/release/nlp-utils ./app/nlp-utils
      
    - name: dl-libtorch
      run: wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.0.1%2Bcpu.zip


    # heroku deployment
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
      # key from repository secrets
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        # name of the Heroku app
        heroku_app_name: "nlp-utils"
        # email from which the app is uploaded
        heroku_email: "hanss.bruno@gmail.com"

        # app directory
        appdir: "./app"

        # start command
        procfile: "web: ./nlp-utils"
        # buildpack is like environment used to run the app
        buildpack: "https://github.com/ph3nx/heroku-binary-buildpack.git"
